# Generated by Django 6.0.4 on 2026-05-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_matricula_programa_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CO', 'Coordinador de Programa'), ('GC', 'Gestor del Conocimiento'), ('ES', 'Estudiante'), ('TI', 'Técnico de Soporte')], max_length=2),
        ),
    ]
