# Generated by Django 6.0.4 on 2026-05-02 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_usuario_rol'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='gestores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'GC'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='api_app_usuario_groups', related_query_name='api_app_usuario', to='auth.group', verbose_name='groups'),
        ),
    ]
