# Generated by Django 6.0.4 on 2026-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_asignatura_semestre_alter_asignatura_gestores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='semestre',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
